import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { PropsWithChildren } from 'react';
import { Footer } from '~/components/footer';
import { Navbar } from '~/components/navbar';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={'antialiased'}>
        <Navbar />
        <main className='w-full'>
          {children}
          <Footer />
        </main>
        {/* <Toaster
          richColors
          expand
          closeButton
          theme="system"
          position="bottom-right"
        /> */}
      </body>
    </html>
  );
}
