/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NomadslandIndexRouteImport } from './routes/nomadsland/index'
import { Route as NomadslandSlugRouteImport } from './routes/nomadsland/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NomadslandIndexRoute = NomadslandIndexRouteImport.update({
  id: '/nomadsland/',
  path: '/nomadsland/',
  getParentRoute: () => rootRouteImport,
} as any)
const NomadslandSlugRoute = NomadslandSlugRouteImport.update({
  id: '/nomadsland/$slug',
  path: '/nomadsland/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/faq': typeof FaqRoute
  '/policy': typeof PolicyRoute
  '/terms': typeof TermsRoute
  '/nomadsland/$slug': typeof NomadslandSlugRoute
  '/nomadsland': typeof NomadslandIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/faq': typeof FaqRoute
  '/policy': typeof PolicyRoute
  '/terms': typeof TermsRoute
  '/nomadsland/$slug': typeof NomadslandSlugRoute
  '/nomadsland': typeof NomadslandIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutRoute
  '/error': typeof ErrorRoute
  '/faq': typeof FaqRoute
  '/policy': typeof PolicyRoute
  '/terms': typeof TermsRoute
  '/nomadsland/$slug': typeof NomadslandSlugRoute
  '/nomadsland/': typeof NomadslandIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/about'
    | '/error'
    | '/faq'
    | '/policy'
    | '/terms'
    | '/nomadsland/$slug'
    | '/nomadsland'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/error'
    | '/faq'
    | '/policy'
    | '/terms'
    | '/nomadsland/$slug'
    | '/nomadsland'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/about'
    | '/error'
    | '/faq'
    | '/policy'
    | '/terms'
    | '/nomadsland/$slug'
    | '/nomadsland/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AboutRoute: typeof AboutRoute
  ErrorRoute: typeof ErrorRoute
  FaqRoute: typeof FaqRoute
  PolicyRoute: typeof PolicyRoute
  TermsRoute: typeof TermsRoute
  NomadslandSlugRoute: typeof NomadslandSlugRoute
  NomadslandIndexRoute: typeof NomadslandIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomadsland/': {
      id: '/nomadsland/'
      path: '/nomadsland'
      fullPath: '/nomadsland'
      preLoaderRoute: typeof NomadslandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nomadsland/$slug': {
      id: '/nomadsland/$slug'
      path: '/nomadsland/$slug'
      fullPath: '/nomadsland/$slug'
      preLoaderRoute: typeof NomadslandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AboutRoute: AboutRoute,
  ErrorRoute: ErrorRoute,
  FaqRoute: FaqRoute,
  PolicyRoute: PolicyRoute,
  TermsRoute: TermsRoute,
  NomadslandSlugRoute: NomadslandSlugRoute,
  NomadslandIndexRoute: NomadslandIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
